# Generated by Django 5.2 on 2025-04-30 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_course_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prise',
            new_name='price',
        ),
    ]
